### ISSUE TITLE
Premium Settings Error: Failed to change sync settings

### ISSUE THREAD

**Issue by aspiers** [rotki/rotki#1187]
## Problem Definition

I built a fresh dev environment on a machine where I've never used Rotki before.  Then I created a new account, and after logging in, set up my Rotki Premium API keys.  But when I click the toggle button "Allow data sync with Rotkehlchen Server" (which BTW should be renamed to "Allow data sync with Rotki Server" because people won't know what Rotkehlchen is), I get:
    
![image](https://user-images.githubusercontent.com/100738/88107346-d9594900-cb9e-11ea-8096-876665653d9d.png)

Log file has:

```
21/07/2020 22:17:58 BST -- INFO:rotkehlchen.api.server.pywsgi:127.0.0.1 - - [2020-07-21 22:17:58] "GET /api/1/messages/ HTTP/1.1" 200 245 0.001985
21/07/2020 22:17:58 BST -- DEBUG:rotkehlchen.api.rest:Request successful response={"result": {"last_balance_save": 1595365275, "eth_node_connection": false, "history_process_start_ts": -1, "history_process_current_ts": -1}, "message": ""}, status_code=200
21/07/2020 22:17:58 BST -- INFO:rotkehlchen.api.server.pywsgi:127.0.0.1 - - [2020-07-21 22:17:58] "GET /api/1/periodic/ HTTP/1.1" 200 345 0.001522
21/07/2020 22:18:03 BST -- DEBUG:rotkehlchen.api.rest:Request successful response={"result": {"warnings": [], "errors": []}, "message": ""}, status_code=200
21/07/2020 22:18:03 BST -- INFO:rotkehlchen.api.server.pywsgi:127.0.0.1 - - [2020-07-21 22:18:03] "GET /api/1/messages/ HTTP/1.1" 200 245 0.001976
21/07/2020 22:18:03 BST -- DEBUG:rotkehlchen.api.rest:Request successful response={"result": {"last_balance_save": 1595365275, "eth_node_connection": false, "history_process_start_ts": -1, "history_process_current_ts": -1}, "message": ""}, status_code=200
21/07/2020 22:18:03 BST -- INFO:rotkehlchen.api.server.pywsgi:127.0.0.1 - - [2020-07-21 22:18:03] "GET /api/1/periodic/ HTTP/1.1" 200 345 0.001935
21/07/2020 22:18:06 BST -- DEBUG:rotkehlchen.rotkehlchen:Main loop start
21/07/2020 22:18:06 BST -- DEBUG:rotkehlchen.rotkehlchen:Main loop end
21/07/2020 22:18:06 BST -- DEBUG:rotkehlchen.rotkehlchen:Main loop start
21/07/2020 22:18:06 BST -- DEBUG:rotkehlchen.rotkehlchen:Main loop end
```

(and BTW it seems that the pywsgi log format is duplicating timestamps somehow).

### System Description

This is with 51f977222c51debe3540babdc813d1d987e790b0 on Linux (openSUSE Tumbleweed).

**Comment by LefterisJP** [comment]
I can reproduce and will try to see if I can fix quick for 1.6.0

**Comment by LefterisJP** [comment]
> (and BTW it seems that the pywsgi log format is duplicating timestamps somehow).

Indeed. It's been like that forever. Perhaps need to have an issue for that to remind us too :)

**Comment by LefterisJP** [comment]
@aspiers #1188 should solve the problem you see. This was introduced between 1.5.0 and 1.6.0 I think due to some changes in the way the settings API works and not all frontend code seems to have been adjusted.

Am just waiting for someone else from the frontend to check the code and give the green light to merge.

**Comment by aspiers** [comment]
Thanks, yes this fixes it - however my portfolio is still not syncing.  Am I supposed to do something else to trigger the sync?

**Comment by isidorosp** [comment]
Are you using the same password in both accounts? This is necessary since the decryption happens locally.

**Comment by LefterisJP** [comment]
What does the log say @aspiers ?

**Comment by aspiers** [comment]
> Are you using the same password in both accounts? This is necessary since the decryption happens locally.

Are you sure this is necessary? If so #1139 was resolved in the wrong way. Currently they are different for me due to that, and I think it is good that it is possible to change the online password, and perhaps also more secure if there are different passwords for different parts of the service.

**Comment by LefterisJP** [comment]
@aspiers yes this is necessary. But funny you don't get an error for this.

The website password is completely different from the password you have on your local account. The local account password is only for the local database. The website password is just so you can access the website and manage you API key and your subscription.

When you encrypt the database you encrypt it with the password you have locally, the one you make for the local account. If it's transferred and synced it needs to be decrypted. The only way for this to happen is for the same password to be used.

**Comment by aspiers** [comment]
Ohhh OK I understand now.  When @isidorosp asked "Are you using the same password in both accounts?" I thought "both" was referring to online vs. offline (local), but it was actually referring to the two offline passwords on the two different machines I am using.  When starting Rotki on a new computer, I don't remember seeing any notification that I should reuse my existing password from the other computer, so maybe I didn't do that.  I'll have to check.  But shouldn't there be a notification if it's necessary?

**Comment by LefterisJP** [comment]
> But shouldn't there be a notification if it's necessary?

There is one when creating a new account if you click the "premium keys" option. You can add premium keys from the get-go when creating an account. And then it pulls data right from the creation of the account.

**Comment by aspiers** [comment]
OK thanks.  I see that notification now; I think it's a little too easy to miss though.  I'll file a separate issue about that.
