### ISSUE TITLE
CDC Import of CSV

### ISSUE THREAD

**Issue by Blackswan122** [rotki/rotki#2024]
"Invalid CSV format, missing required field: 'debited'"

I can't change anything to get debited field

Operating system: Win 10 64
Rotki version: 1.11.0

**Comment by LefterisJP** [comment]
Is this for the Crypto.com import? 

This is only for the mobile app's data that @CPatchane implemented for his own use case and added it to the app in case others can benefit.

@CPatchane that is correct right? Or did @Blackswan122 find a bug? Or did crypto.com just change their csv format?

**Comment by Blackswan122** [comment]
I just saved my CSV file and imported it. I do have dust conversiosions and MCO/CRO swap everyone will have as it was forced on everyone.

**Comment by LefterisJP** [comment]
@Blackswan122 the question is where did you save the CSV file from? If this is from the mobile app then it should work. If it is from the website then it will not work as the website is not supported.

**Comment by CPatchane** [comment]
True. Is it possible to get those rows without amounts to help debugging 🙏 ? You can join the rotki discord if you prefer to share direct to me in private.

**Comment by LefterisJP** [comment]
@Blackswan122 so which service's CSV file did you try to export? Would like to know here to see what needs to be done with this issue.

**Comment by Blackswan122** [comment]
I just tried it again.....downloaded from Mobile app the CSV file. Sent it per email...loaded file from downloads and got the error 
"Invalid CSV format, missing required field 'debited'

There's nothing for me to chose in CDC app except download CSV

**Comment by LefterisJP** [comment]
@Blackswan122 thank you. So it is indeed from the mobile app then I understand. So @CPatchane there is a bug in the importer or they changed their format.

@Blackswan122  Can you maybe DM me in discord or twitter how the csv file looks like. This is why dislike supporting CSV imports. The format can change at any time.

**Comment by Blackswan122** [comment]
Timestamp (UTC)	Transaction Description	Currency	Amount	To Currency	To Amount	Native Currency	Native Amount	Native Amount (in USD)	Transaction Kind

Here are the current headers of CSV file

**Comment by LefterisJP** [comment]
@CPatchane any idea why he would get different CSV format than you? He is also using the mobile app.

**Comment by CPatchane** [comment]
Headers from @Blackswan122 are good and are the same than the one I have and the one from the tests.
I get the issue I think, do you have at a moment two `dust_conversion_debited` lines followed by only one `dust_conversion_credited`? They should have the exact timestamp.
@LefterisJP CDC seems to gather dust conversions in one credited line, the script about double entries is working by matching 1:1 for credited and debited lines. I have to add that case then.

**Comment by LefterisJP** [comment]
@CPatchane I see. When you can handle this we can close the issue

**Comment by LefterisJP** [comment]
Should be fixed by #2150

**Comment by Blackswan122** [comment]
I noticed there are 3 files to download from CDC mobile App Fiat crypto and Card. Fiat and card work fine. Rotki says loaded but the crypto csv still fails.

**Comment by LefterisJP** [comment]
The fix is not live yet. It will be included in the next release.

**Comment by Blackswan122** [comment]
I still have this problem Exporting the file Crypto Transactions into Rotki. The other 2 work. It has never worked. To confirm this file is from the mobile App not the exchange. 
![CDC Debited](https://user-images.githubusercontent.com/59722401/111911238-fd8a6400-8a64-11eb-8005-af89794f6397.PNG)

**Comment by LefterisJP** [comment]
Hey @Blackswan122. Another user is also having similar problems but with a different field in this issue: https://github.com/rotki/rotki/issues/2529

Can you also add an example (you can fake the actual data -- but please make them still make sense) of each file you are trying to upload so we can find out all possible data types we may be missing?

**Comment by Blackswan122** [comment]
![CDC Example](https://user-images.githubusercontent.com/59722401/111914906-3d0c7c80-8a74-11eb-9db4-851bfe2cf953.PNG)
This is what the headers look like

**Comment by Blackswan122** [comment]
It's only the Crypto transactions that doesn't load. The other two do..

**Comment by LefterisJP** [comment]
Can you add them as a CSV text file in the other issue I pointed? Can't take the data from a screenshot.

**Comment by Blackswan122** [comment]
I tried to upload CSV Excel but it says 'don't 

support that file type'
